# Generated by Django 3.2.6 on 2021-08-31 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_register_phoneno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
    ]
