# Generated by Django 3.2.6 on 2021-09-01 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_us'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='us',
            new_name='ash',
        ),
    ]
