# Generated by Django 3.2.6 on 2021-08-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cartlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartid', models.CharField(max_length=225, unique=True)),
                ('cartdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
