# Generated by Django 3.2.6 on 2021-08-24 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, unique=True)),
                ('slug', models.SlugField(max_length=225, unique=True)),
                ('img', models.ImageField(upload_to='product')),
                ('des', models.TextField()),
                ('stock', models.IntegerField()),
                ('available', models.BooleanField()),
                ('price', models.IntegerField()),
                ('cata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.catag')),
            ],
        ),
    ]
